### ISSUE TITLE
[TODO] Mass-Moderate content

### ISSUE THREAD

**Issue by seahindeniz** [seahindeniz/BrainlyTools_Extension#74]
We need a panel for moderating contents ideally in one place. So all requests that related to the contents, will be gathered in here. 

So below, there are several option specified that we can use it in the panel. How we can set target contents, what type of contents we have, what we can do and how we can filter(if possible).

Content types:
<sub><i>What kind of contents we can moderate</i></sup>
- [x] Questions
- [x] Answers
- [x] Comments

Inputs:
<sub><i>Where users can specify targets</i></sup>
- [x] List of ids <sub><i>User can paste list of id numbers of targeted contents</i></sup>
- [x] Id range <sub> Like, id numbers between and including `965235 : 850025`.<i> User can specify targets by typing two id numbers separated by a semicolon</i></sup>
- Questions only
  - [ ] Searching questions <sub><i>Ability to search questions</i></sup>

Methods:
<sub><i>How we can moderate</i></sup>
- [x] Report(for abuse) contents #70
- [ ] Delete contents
- Answers only
  - [ ] Ask for correction (only for answers)
  - [ ] Approve

Possible filters:
- [ ] by owner
- [ ] by date

> Functionality of filters will be limited. Because extension cannot customize the queries to fetch specified details from databases of Brainly. Filters would only works on fetched details of listed contents.
